### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by jonasagx** [maciek134/node-mpg123#1]
Is there a signal to increase the volume? It's not a issue related to your code, I just hope you might know that. Thanks, anyway.

**Comment by maciek134** [comment]
Wow, I need to update this lib, thanks for reminding me about it. There is no signal for that, you send `+` or `-` keys to the standard input (and I need to change the code so it uses this kind of control rather than the signal one).

**Comment by jonasagx** [comment]
Got it, thanks.
